"""Curated LinkedIn skills bundle.

Skills commonly found on LinkedIn profiles across technical and professional
categories. This is an offline bundle that does not require API access.
"""

LINKEDIN_SKILLS: tuple[str, ...] = (
    # Soft Skills & Professional Competencies
    "Leadership",
    "Communication",
    "Teamwork",
    "Problem Solving",
    "Critical Thinking",
    "Creativity",
    "Adaptability",
    "Time Management",
    "Collaboration",
    "Emotional Intelligence",
    "Conflict Resolution",
    "Decision Making",
    "Strategic Thinking",
    "Negotiation",
    "Presentation Skills",
    "Public Speaking",
    "Active Listening",
    "Mentoring",
    "Coaching",
    "Facilitation",
    "Persuasion",
    "Networking",
    "Relationship Building",
    "Customer Service",
    "Stakeholder Management",
    "Change Management",
    "Organizational Skills",
    "Attention to Detail",
    "Self-Motivation",
    "Work Ethic",
    "Resilience",
    "Empathy",
    "Cultural Awareness",
    "Interpersonal Skills",
    "Written Communication",
    "Verbal Communication",
    "Cross-functional Collaboration",
    "Analytical Thinking",
    "Research",
    "Innovation",
    "Continuous Learning",
    "Accountability",
    "Integrity",
    # Management & Leadership
    "Team Management",
    "People Management",
    "Performance Management",
    "Strategic Planning",
    "Organizational Development",
    "Executive Leadership",
    "P&L Management",
    "Budget Management",
    "Resource Allocation",
    "Risk Management",
    "Program Management",
    "Portfolio Management",
    "Operations Management",
    "Business Strategy",
    "Corporate Strategy",
    "Change Leadership",
    "Talent Development",
    "Succession Planning",
    "Employee Engagement",
    "Culture Building",
    "Vision Setting",
    "Crisis Management",
    "Mergers and Acquisitions",
    "Business Development",
    "Partnership Development",
    "Vendor Management",
    "Contract Negotiation",
    "Executive Communication",
    # Marketing
    "Digital Marketing",
    "Content Marketing",
    "Social Media Marketing",
    "SEO",
    "SEM",
    "Google Analytics",
    "Email Marketing",
    "Inbound Marketing",
    "Brand Management",
    "Market Research",
    "Marketing Strategy",
    "Product Marketing",
    "Growth Hacking",
    "Conversion Rate Optimization",
    "A/B Testing",
    "Copywriting",
    "Content Strategy",
    "Influencer Marketing",
    "Affiliate Marketing",
    "Marketing Automation",
    "HubSpot",
    "Marketo",
    "Google Ads",
    "Facebook Ads",
    "LinkedIn Ads",
    "Campaign Management",
    "Media Planning",
    "Public Relations",
    "Event Marketing",
    "Video Marketing",
    "Podcast Marketing",
    "Community Management",
    "Customer Acquisition",
    "Retention Marketing",
    # Finance & Accounting
    "Financial Analysis",
    "Accounting",
    "Budgeting",
    "Financial Modeling",
    "Financial Reporting",
    "Forecasting",
    "Variance Analysis",
    "Cost Analysis",
    "Revenue Analysis",
    "Cash Flow Management",
    "Financial Planning",
    "Investment Analysis",
    "Risk Analysis",
    "Mergers & Acquisitions",
    "Due Diligence",
    "Valuation",
    "Corporate Finance",
    "Private Equity",
    "Venture Capital",
    "Audit",
    "Tax Planning",
    "GAAP",
    "IFRS",
    "Excel Financial Modeling",
    "QuickBooks",
    "SAP Finance",
    "Oracle Financials",
    "Treasury Management",
    "Credit Analysis",
    # Design & UX
    "UI Design",
    "UX Design",
    "User Research",
    "Wireframing",
    "Prototyping",
    "Figma",
    "Sketch",
    "Adobe XD",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe InDesign",
    "Graphic Design",
    "Visual Design",
    "Motion Graphics",
    "Typography",
    "Color Theory",
    "Brand Identity",
    "Design Systems",
    "Accessibility Design",
    "Information Architecture",
    "Interaction Design",
    "Design Thinking",
    "Usability Testing",
    "User Personas",
    "Journey Mapping",
    "Responsive Design",
    "Style Guides",
    "Invision",
    "Zeplin",
    "Canva",
    "After Effects",
    "Premiere Pro",
    "3D Design",
    "Blender",
    # Sales
    "Sales",
    "Sales Management",
    "Account Management",
    "CRM",
    "Salesforce CRM",
    "Cold Calling",
    "Lead Generation",
    "Pipeline Management",
    "Sales Strategy",
    "Enterprise Sales",
    "Inside Sales",
    "Field Sales",
    "Channel Sales",
    "Solution Selling",
    "Consultative Selling",
    "Sales Forecasting",
    "Territory Management",
    "Key Account Management",
    "Customer Success",
    "Upselling",
    "Cross-selling",
    "Proposal Writing",
    "RFP Response",
    "Sales Enablement",
    # Human Resources
    "Recruiting",
    "Talent Acquisition",
    "Talent Management",
    "HR Management",
    "Onboarding",
    "Employee Relations",
    "Compensation and Benefits",
    "HRIS",
    "Workday",
    "ATS Systems",
    "Diversity and Inclusion",
    "Workforce Planning",
    "Learning and Development",
    "Training Design",
    "Instructional Design",
    "Employer Branding",
    "HR Policies",
    "Labor Relations",
    "Organizational Design",
    "Job Analysis",
    "Performance Reviews",
    "Employee Retention",
    # Engineering (Non-Software)
    "Mechanical Engineering",
    "Electrical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Industrial Engineering",
    "Manufacturing Engineering",
    "Aerospace Engineering",
    "Systems Engineering",
    "Product Design",
    "CAD",
    "CAM",
    "Lean Manufacturing",
    "Six Sigma",
    "Quality Assurance",
    "Quality Control",
    "ISO 9001",
    "Process Improvement",
    "Supply Chain Management",
    "Logistics",
    "Procurement",
    "Operations Research",
    "Simulation",
    "Structural Analysis",
    "Finite Element Analysis",
    # Healthcare & Life Sciences
    "Clinical Research",
    "Patient Care",
    "Healthcare Management",
    "Electronic Health Records",
    "Medical Coding",
    "Regulatory Affairs",
    "Clinical Trials",
    "Drug Development",
    "Pharmacovigilance",
    "Medical Writing",
    "Bioinformatics",
    "Genomics",
    "Proteomics",
    "Laboratory Skills",
    "GMP",
    "FDA Compliance",
    "HIPAA Compliance",
    "Healthcare Analytics",
    "Public Health",
    "Epidemiology",
    # Legal
    "Contract Law",
    "Compliance",
    "Corporate Law",
    "Intellectual Property",
    "Litigation",
    "Legal Research",
    "Contract Drafting",
    "Regulatory Compliance",
    "Employment Law",
    "Privacy Law",
    "Data Protection",
    "Mergers & Acquisitions Law",
    "Legal Writing",
    "Risk and Compliance",
    # Education & Training
    "Curriculum Development",
    "E-Learning",
    "Training Delivery",
    "Workshop Facilitation",
    "Educational Technology",
    "Classroom Management",
    "Assessment Design",
    "Academic Research",
    "Grant Writing",
    "Technical Writing",
    "Editing",
    "Proofreading",
    # Technology (overlap with O*NET fine — dedup in pipeline)
    "Python",
    "JavaScript",
    "Java",
    "SQL",
    "Data Analysis",
    "Machine Learning",
    "Artificial Intelligence",
    "Data Science",
    "Cloud Computing",
    "Cybersecurity",
    "Software Development",
    "Web Development",
    "Mobile Development",
    "Product Management",
    "Agile Methodology",
    "Scrum",
    "DevOps",
    "APIs",
    "Databases",
    "Business Intelligence",
    "Data Visualization",
    "ETL",
    "Data Engineering",
    "Statistics",
    "R",
    "Tableau",
    "Power BI",
    "Excel",
    "Microsoft Office",
    "Google Workspace",
    "Project Management",
    "JIRA",
    "Confluence",
    "Slack",
    "Zoom",
    "Microsoft Teams",
    "Salesforce",
    "SAP",
    "ERP Systems",
    "Linux",
    "Windows",
    "macOS",
    "IT Support",
    "Help Desk",
    "System Administration",
    "Network Administration",
    "Technical Support",
    "Troubleshooting",
    "IT Infrastructure",
    "Cloud Architecture",
    "Solution Architecture",
    "Enterprise Architecture",
    "Data Governance",
    "Master Data Management",
    "Data Quality",
    "Data Warehousing",
    "Business Analysis",
    "Requirements Gathering",
    "Systems Analysis",
    "Process Mapping",
    "Workflow Automation",
    "RPA",
    "Low-Code Development",
    "No-Code Development",
    "Chatbots",
    "Natural Language Processing",
    "Computer Vision",
    "Deep Learning",
    "Neural Networks",
    "Predictive Analytics",
    "Prescriptive Analytics",
    "Descriptive Analytics",
    "Experimentation",
    "Product Analytics",
    "Web Analytics",
    "Customer Analytics",
    "Retention Analysis",
    "Cohort Analysis",
    "Funnel Analysis",
    # Communication & Media
    "Journalism",
    "Content Creation",
    "Blogging",
    "Video Production",
    "Photography",
    "Podcasting",
    "Social Media Management",
    "Community Building",
    "Brand Storytelling",
    "Thought Leadership",
    "Executive Presence",
    # Consulting & Strategy
    "Management Consulting",
    "Strategy Consulting",
    "Business Transformation",
    "Digital Transformation",
    "IT Consulting",
    "Process Consulting",
    "Organizational Change",
    "Benchmarking",
    "Competitive Analysis",
    "SWOT Analysis",
    "Business Case Development",
    "Feasibility Analysis",
    "KPI Development",
    "OKRs",
    "Balanced Scorecard",
    # Real Estate & Construction
    "Real Estate",
    "Property Management",
    "Construction Management",
    "Project Scheduling",
    "Cost Estimation",
    "Building Information Modeling",
    "Urban Planning",
)
