"""Curated O*NET technology skills bundle.

Skills sourced from O*NET Technology Skills and Tools & Technology
categories. This is an offline bundle that does not require API access.
"""

ONET_SKILLS: tuple[str, ...] = (
    # Programming Languages
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "C",
    "C++",
    "C#",
    "Go",
    "Rust",
    "Ruby",
    "PHP",
    "Swift",
    "Kotlin",
    "Scala",
    "R",
    "MATLAB",
    "Perl",
    "Haskell",
    "Erlang",
    "Elixir",
    "Clojure",
    "F#",
    "Dart",
    "Lua",
    "Julia",
    "Groovy",
    "COBOL",
    "Fortran",
    "Assembly",
    "Visual Basic",
    "Objective-C",
    "Shell",
    "Bash",
    "PowerShell",
    "Tcl",
    "Scheme",
    "Lisp",
    "Prolog",
    "VHDL",
    "Verilog",
    # Web Technologies
    "HTML",
    "CSS",
    "SASS",
    "LESS CSS",
    "XML",
    "JSON",
    "YAML",
    "REST",
    "GraphQL",
    "gRPC",
    "WebSockets",
    "HTTP",
    "HTTPS",
    "OAuth",
    "JWT",
    "OpenAPI",
    "Swagger",
    "SOAP",
    "WSDL",
    # Frontend Frameworks & Libraries
    "React",
    "Vue",
    "Angular",
    "Svelte",
    "Next.js",
    "Nuxt.js",
    "Gatsby",
    "Redux",
    "MobX",
    "jQuery",
    "Bootstrap",
    "Tailwind CSS",
    "Material UI",
    "Chakra UI",
    "Webpack",
    "Vite",
    "Babel",
    "ESLint",
    "Prettier",
    "Jest",
    "Cypress",
    "Playwright",
    "Storybook",
    # Backend Frameworks
    "Django",
    "Flask",
    "FastAPI",
    "Spring",
    "Spring Boot",
    "Express",
    "NestJS",
    "Rails",
    "Laravel",
    "Symfony",
    "ASP.NET",
    "ASP.NET Core",
    "Gin",
    "Echo",
    "Fiber",
    "Actix",
    "Rocket",
    "Phoenix",
    "Ktor",
    "Micronaut",
    "Quarkus",
    "Tornado",
    "Sanic",
    "Starlette",
    "aiohttp",
    # Databases
    "SQL",
    "NoSQL",
    "PostgreSQL",
    "MySQL",
    "SQLite",
    "MariaDB",
    "Oracle Database",
    "Microsoft SQL Server",
    "MongoDB",
    "Redis",
    "Elasticsearch",
    "DynamoDB",
    "Cassandra",
    "CouchDB",
    "Firebase",
    "Firestore",
    "Neo4j",
    "InfluxDB",
    "TimescaleDB",
    "Snowflake",
    "BigQuery",
    "Redshift",
    "Databricks",
    "HBase",
    "Memcached",
    "RethinkDB",
    "ArangoDB",
    "Couchbase",
    # Cloud Platforms
    "AWS",
    "Azure",
    "GCP",
    "Google Cloud Platform",
    "Amazon Web Services",
    "Microsoft Azure",
    "EC2",
    "S3",
    "Lambda",
    "RDS",
    "ECS",
    "EKS",
    "CloudFormation",
    "CloudWatch",
    "IAM",
    "VPC",
    "Route 53",
    "CloudFront",
    "API Gateway",
    "SQS",
    "SNS",
    "Kinesis",
    "Glue",
    "Athena",
    "Sagemaker",
    "Azure DevOps",
    "Azure Functions",
    "Azure Kubernetes Service",
    "Azure Blob Storage",
    "Azure Active Directory",
    "Google Kubernetes Engine",
    "Google Cloud Storage",
    "Cloud Run",
    "Cloud Functions",
    "Pub/Sub",
    "Heroku",
    "DigitalOcean",
    "Linode",
    "Cloudflare",
    # DevOps & Infrastructure
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "Jenkins",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "GitHub Actions",
    "GitLab CI",
    "CircleCI",
    "Travis CI",
    "ArgoCD",
    "Helm",
    "Prometheus",
    "Grafana",
    "ELK Stack",
    "Logstash",
    "Kibana",
    "Datadog",
    "New Relic",
    "PagerDuty",
    "Splunk",
    "Nginx",
    "Apache",
    "HAProxy",
    "Vault",
    "Consul",
    "Istio",
    "Envoy",
    "Linkerd",
    "Puppet",
    "Chef",
    "SaltStack",
    "Pulumi",
    "CDK",
    "Vagrant",
    "Packer",
    # Data Science & Machine Learning
    "TensorFlow",
    "PyTorch",
    "Keras",
    "scikit-learn",
    "pandas",
    "NumPy",
    "SciPy",
    "Matplotlib",
    "Seaborn",
    "Plotly",
    "Jupyter",
    "Apache Spark",
    "Hadoop",
    "Hive",
    "Pig",
    "Kafka",
    "Airflow",
    "dbt",
    "MLflow",
    "Kubeflow",
    "Hugging Face",
    "NLTK",
    "spaCy",
    "OpenCV",
    "XGBoost",
    "LightGBM",
    "CatBoost",
    "Statsmodels",
    "NetworkX",
    "Dask",
    "Ray",
    "CUDA",
    "OpenCL",
    # Operating Systems
    "Linux",
    "Unix",
    "Windows Server",
    "macOS",
    "Ubuntu",
    "CentOS",
    "Red Hat Enterprise Linux",
    "Debian",
    "Fedora",
    "Alpine Linux",
    "FreeBSD",
    # Networking
    "TCP/IP",
    "DNS",
    "DHCP",
    "BGP",
    "OSPF",
    "VPN",
    "Load Balancing",
    "Firewall",
    "NAT",
    "SDN",
    "Network Security",
    "Wireshark",
    "Cisco",
    "Juniper",
    "SD-WAN",
    "CDN",
    "SSL/TLS",
    # Security
    "Encryption",
    "Penetration Testing",
    "OWASP",
    "SIEM",
    "SOC",
    "Vulnerability Assessment",
    "Incident Response",
    "Identity and Access Management",
    "Zero Trust",
    "PKI",
    "SAST",
    "DAST",
    "DevSecOps",
    "Threat Modeling",
    "Compliance",
    "GDPR",
    "SOC 2",
    "ISO 27001",
    "PCI DSS",
    "HIPAA",
    "NIST",
    "CIS Controls",
    # Testing & QA
    "Unit Testing",
    "Integration Testing",
    "End-to-End Testing",
    "Test Automation",
    "Selenium",
    "Appium",
    "JUnit",
    "pytest",
    "Mocha",
    "Jasmine",
    "TestNG",
    "Cucumber",
    "BDD",
    "TDD",
    "Load Testing",
    "Performance Testing",
    "JMeter",
    "k6",
    "Gatling",
    # Project Management
    "Project Management",
    "Agile",
    "Scrum",
    "Kanban",
    "Jira",
    "Confluence",
    "Trello",
    "Asana",
    "Monday.com",
    "Waterfall",
    "SAFe",
    "LeSS",
    "Lean",
    "Six Sigma",
    "PMP",
    "Prince2",
    # Business & Productivity Tools
    "Microsoft Excel",
    "Microsoft Office",
    "Google Workspace",
    "Salesforce",
    "SAP",
    "ServiceNow",
    "Tableau",
    "Power BI",
    "Looker",
    "Qlik",
    "LabVIEW",
    # Version Control & Collaboration
    "SVN",
    "Mercurial",
    "Code Review",
    "Pull Requests",
    "Branching Strategies",
    "GitFlow",
    "Trunk-Based Development",
    # API & Integration
    "Microservices",
    "Event-Driven Architecture",
    "Message Queues",
    "RabbitMQ",
    "Apache Kafka",
    "MQTT",
    "Protocol Buffers",
    "Avro",
    "JSON Schema",
    "API Design",
    "Webhooks",
    # CAD & Engineering Tools
    "AutoCAD",
    "SolidWorks",
    "CATIA",
    "Ansys",
    "Abaqus",
    # Mobile Development
    "iOS Development",
    "Android Development",
    "React Native",
    "Flutter",
    "Xamarin",
    "Ionic",
    "Xcode",
    "Android Studio",
    # Embedded & Systems
    "Embedded Systems",
    "RTOS",
    "Firmware",
    "Arduino",
    "Raspberry Pi",
    "FPGA",
    "PLC",
    # Methodologies & Practices
    "CI/CD",
    "DevOps",
    "MLOps",
    "DataOps",
    "Site Reliability Engineering",
    "Platform Engineering",
    "Infrastructure as Code",
    "GitOps",
    "Observability",
    "Distributed Systems",
    "System Design",
    "Software Architecture",
    "Domain-Driven Design",
    "SOLID Principles",
    "Design Patterns",
    "Microservices Architecture",
    "Event Sourcing",
    "CQRS",
    "Serverless",
    # Blockchain & Emerging Tech
    "Blockchain",
    "Ethereum",
    "Smart Contracts",
    "Solidity",
    "Web3",
    "IoT",
    "Edge Computing",
    "Quantum Computing",
    "AR/VR",
    "Computer Vision",
    "Natural Language Processing",
    "Generative AI",
    "Large Language Models",
    "Prompt Engineering",
)
